#!/bin/bash

# =========================================================
# Compile all .tex files recursively to PDF and DOCX
# Then remove LaTeX temporary files
#
# Features:
#   - PDF via pdflatex
#   - DOCX via pandoc
#   - auto-detects when --shell-escape is needed
#   - checks for xlsx2csv if the .tex uses \ShellEscape + xlsx2csv
#   - skips DOCX for auto-generated LaTeX table workflows that pandoc
#     does not handle well
#   - removes common LaTeX temp files after compilation
#   - removes tmp_*.csv files generated during LaTeX compilation
# =========================================================

ROOT="${1:-.}"

echo "=================================================="
echo "LaTeX Batch Compiler"
echo "Root folder: $ROOT"
echo "=================================================="
echo ""

PDF_OK=0
PDF_FAIL=0
DOCX_OK=0
DOCX_FAIL=0
DOCX_SKIP=0

# Check dependencies
if ! command -v pdflatex >/dev/null 2>&1; then
    echo "ERROR: pdflatex not found"
    exit 1
fi

if ! command -v pandoc >/dev/null 2>&1; then
    echo "ERROR: pandoc not found"
    exit 1
fi

mapfile -t TEX_FILES < <(find "$ROOT" -type f -name "*.tex" ! -path "*/.*/*" | sort)

echo "Found ${#TEX_FILES[@]} .tex file(s)"
echo ""

clean_temp() {
    local dir="$1"
    local base="$2"

    rm -f \
        "$dir/$base.aux" \
        "$dir/$base.log" \
        "$dir/$base.out" \
        "$dir/$base.toc" \
        "$dir/$base.lot" \
        "$dir/$base.lof" \
        "$dir/$base.fls" \
        "$dir/$base.fdb_latexmk" \
        "$dir/$base.synctex.gz" \
        "$dir/$base.bbl" \
        "$dir/$base.blg" \
        "$dir/$base.nav" \
        "$dir/$base.snm" \
        "$dir/$base.vrb" \
        "$dir/$base.run.xml" \
        "$dir/$base.xdv" \
        "$dir/$base.latexmk" \
        "$dir/$base.acn" \
        "$dir/$base.acr" \
        "$dir/$base.alg" \
        "$dir/$base.glg" \
        "$dir/$base.glo" \
        "$dir/$base.gls" \
        "$dir/$base.ist"

    # Remove XLSX -> CSV temp files generated by shell-escape workflows
    rm -f "$dir"/tmp_*.csv
}

needs_shell_escape() {
    local texfile="$1"
    if grep -Eq '\\ShellEscape\{|write18|immediate\\write18' "$texfile"; then
        return 0
    fi
    return 1
}

needs_xlsx2csv() {
    local texfile="$1"
    if grep -Eq 'xlsx2csv' "$texfile"; then
        return 0
    fi
    return 1
}

docx_should_skip() {
    local texfile="$1"
    if grep -Eq '\\ShellEscape\{|pgfplotstable|xlsx2csv' "$texfile"; then
        return 0
    fi
    return 1
}

for f in "${TEX_FILES[@]}"
do
    dir=$(dirname "$f")
    file=$(basename "$f")
    base="${file%.tex}"

    echo "-------------------------------------------"
    echo "Processing: $f"
    echo "-------------------------------------------"

    PDF_FLAGS=(-interaction=nonstopmode)

    if needs_shell_escape "$f"; then
        PDF_FLAGS+=(--shell-escape)
        echo "[PDF] shell-escape detected -> enabled"

        if needs_xlsx2csv "$f"; then
            if ! command -v xlsx2csv >/dev/null 2>&1; then
                echo "[PDF] ERROR: xlsx2csv needed by $file but not found"
                echo "      Install with: sudo apt install xlsx2csv"
                PDF_FAIL=$((PDF_FAIL+1))

                if docx_should_skip "$f"; then
                    echo "[DOCX] skipped (auto-generated LaTeX tables / shell-escape not suitable for pandoc)"
                    DOCX_SKIP=$((DOCX_SKIP+1))
                else
                    echo "[DOCX] compiling..."
                    pandoc "$f" --from=latex --to=docx -o "$dir/$base.docx" >/dev/null 2>&1
                    if [ -f "$dir/$base.docx" ]; then
                        echo "[DOCX] OK"
                        DOCX_OK=$((DOCX_OK+1))
                    else
                        echo "[DOCX] FAILED"
                        DOCX_FAIL=$((DOCX_FAIL+1))
                    fi
                fi

                clean_temp "$dir" "$base"
                echo ""
                continue
            fi
        fi
    fi

    # ---------- PDF ----------
    echo "[PDF] compiling..."

    (
        cd "$dir" || exit
        pdflatex "${PDF_FLAGS[@]}" "$file" >/dev/null 2>&1
        pdflatex "${PDF_FLAGS[@]}" "$file" >/dev/null 2>&1
    )

    if [ -f "$dir/$base.pdf" ]; then
        echo "[PDF] OK"
        PDF_OK=$((PDF_OK+1))
    else
        echo "[PDF] FAILED"
        PDF_FAIL=$((PDF_FAIL+1))
    fi

    # ---------- DOCX ----------
    if docx_should_skip "$f"; then
        echo "[DOCX] skipped (auto-generated LaTeX tables / shell-escape not suitable for pandoc)"
        DOCX_SKIP=$((DOCX_SKIP+1))
    else
        echo "[DOCX] compiling..."
        pandoc "$f" --from=latex --to=docx -o "$dir/$base.docx" >/dev/null 2>&1

        if [ -f "$dir/$base.docx" ]; then
            echo "[DOCX] OK"
            DOCX_OK=$((DOCX_OK+1))
        else
            echo "[DOCX] FAILED"
            DOCX_FAIL=$((DOCX_FAIL+1))
        fi
    fi

    # ---------- CLEAN ----------
    clean_temp "$dir" "$base"

    echo ""
done

echo "=================================================="
echo "Compilation Summary"
echo "=================================================="
echo "PDF  : OK=$PDF_OK  FAIL=$PDF_FAIL"
echo "DOCX : OK=$DOCX_OK FAIL=$DOCX_FAIL SKIP=$DOCX_SKIP"
echo ""
echo "Temporary LaTeX files removed."
